platform :ios, "8.0"
use_frameworks!
target 'CampusExchange_iOS' do
	pod "AFNetworking" 
    pod 'SDWebImage', '~>3.8'
    pod 'TTTAttributedLabel'
    pod 'TPKeyboardAvoiding'
    pod 'BlocksKit'
    pod 'iOS-Slide-Menu'
    pod 'HMSegmentedControl'
    pod 'MJRefresh'

end